ログイン機能の実装
yanbaru-expert/team_project_56 pull request #31
Opened 2021-07-15 06:17 UTC by 3guna3

close #7

## 実装内容

- `devise`を利用して、ユーザーのログイン機能を実装

- マイグレーションファイルのパスワード再設定関連のカラムをコメントアウト
```ruby
# 次の箇所をコメントアウト

　　## Recoverable
　　t.string   :reset_password_token
　　t.datetime :reset_password_sent_at

# 次の箇所をコメントアウト

　　add_index :users, :reset_password_token, unique: true
```
- パスワード再設定機能を削るため、`User`モデルの`:recoverable`を削除してマイグレーションを実行

- 「全て」のページを「ログイン必須」に変更

- 新規登録・ログイン・アカウント編集・ログアウトのリンクを、全てのページの一番上に追加
  - `application.html.erb`の`header`タグ内にリンクを設置
  - 直接`appilication.html.erb`に書き込まず、部分テンプレート
     `app/views/layouts/_header.html.erb`を作成
  - 条件分岐を利用し、表示内容を工夫

- 以下の書式で`db/seeds.rb`にテスト用ユーザーを作成できるように設定
  - 何度実行してもエラーが出ないように`create!`ではなく`find_or_create_by!`を使用
```ruby
email = 'test@example.com'
password = 'password'

#テストユーザーが存在しないときだけ作成
User.find_or_create_by!(email: email) do |user|
  user.password = password
  puts 'ユーザーの初期データインポートに成功しました。'
end
```

## 参考資料
- [【やんばるエキスパート教材】ログイン機能](https://www.yanbaru-code.com/texts/219)

## チェックリスト

- [ ] `rails db:seed`を実行して初期データを作成
- [ ] Railsサーバーを起動し、トップページにアクセスした際に「ログイン画面」にリダイレクトされることを確認
- [ ] ログイン・ログアウトができるかどうかを確認
- [ ] リンクが適切に表示されていることを確認
- [ ] 「ログイン」ページに「Forgot your password?」のリンクが表示されていない
- [ ] パスワードの再設定のページ (http://lochalhost:3000/users/password/new) にアクセスできないことを確認
- [ ] `bundle exec rubocop -a`を実行して差分がないことを確認

2021-07-15 10:41 UTC, sekiguchi0215 reviewed
`app/views/layouts/application.html.erb` の
```
<%= render 'layouts/header' %>
```
の記述場所が違うと思います。

2021-07-15 15:10 UTC, great084 requested changes
renderの部分を見直してください〜

2021-07-15 15:10 UTC, great084 commented on app/views/layouts/application.html.erb
> +    <%= render 'layouts/header' %>
<head>タグ内部はhtmlのヘッダー情報表示部なので、コンテンツ入れてはいけません。

2021-07-16 12:58 UTC, 3guna3 commented on app/views/layouts/application.html.erb
> +    <%= render 'layouts/header' %>
renderの部分を修正いたしました。
ご確認のほど、よろしくお願いいたします。

2021-07-16 14:03 UTC, great084 approved these changes
LGTMです！

2021-07-17 12:15 UTC, merged