Railsテキスト教材一覧ページの実装
yanbaru-expert/team_project_56 pull request #38
Opened 2021-07-23 17:10 UTC by staygold-teruma

close #16

## 実装内容

-  Railsテキスト教材の一覧ページを作成
-  テキスト教材ページのスタイル用にtexts.scssを作成

## 実装条件
 -  表示するジャンルは Text::RAILS_GENRE_LIST に制限
 -  Bootstrapの Cards や Grid System を用いて下図のようなスタイルにすること
 -  each を使わず「コレクションをレンダリング」を利用しましょう
 -  画像部分は デフォルト画像 を表示するのみとする
 -  カードの height, max-width を指定すること
 -  テキスト教材ページでしか利用しないスタイルは app/assets/stylesheets/texts.scss を作成して書き込むこと
 -  検索機能は実装しない
 -  広告は実装しない
 -  カード全体を「詳細ページ」へのリンクにする作業は別タスクとする
 -  「読破済みボタン」はボタンの配置のみとする。（機能は別タスクで実装）

## 参考資料（必要があれば）

[【公式】Bootstrap Cards](https://getbootstrap.jp/docs/4.5/components/card/)
[【公式】Bootstrap Grid system](https://getbootstrap.jp/docs/4.5/layout/grid/)

## チェックリスト
- [ ] 画像のようにレスポンシブ対応ができているかどうかを確認
- [ ] ブラウザの横幅次第でカードの横幅が長くなりすぎていないか確認
- [ ] PHPのテキスト教材が表示されていないことを確認
- [ ] 上記の実装条件を満たしているか確認
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
- [ ] `rubocop -a` を実行

## 備考
テキスト教材ページのHTMLでBootstrap以外にいくつかクラスを付与しています。
この辺りで問題ありそうであればSlackもしくはMTGで調整お願いします。

2021-07-24 14:10 UTC, great084 requested changes
- 教材一覧のカード内部の画像エリアに余計な空白が存在しています
- 教材のカードの上下の空白が大きいと思います。
![image](https://user-images.githubusercontent.com/36526480/126870833-fcebfed8-bfa6-4c97-b68a-c44ed06ab2ed.png)

※このあたりはチーム開発の模範サイト（https://sample-team-project-y.herokuapp.com/）を見て、スタイルも可能な限り再現してみてください。

- 定義した独自のクラスの中にBootstrapで定義されているクラスがあります。独自のクラスを定義することは問題ありませんが、フレームワークとしてBootstrapを利用しているので、そのまま利用できるものは流用したほうが良いです。
Bootstrapのドキュメントを参照して、代替できるものがないか確認して見てください。

2021-07-24 14:10 UTC, great084 commented on app/assets/stylesheets/texts.scss
> +          height: auto;
bootstrapのimg-fluidクラスが利用できると思います

2021-07-24 14:10 UTC, great084 commented on app/assets/stylesheets/texts.scss
> +          }
bootstrapのbtn-blockクラスが利用できると思います。

2021-07-25 09:53 UTC, sekiguchi0215 commented on app/views/texts/index.html.erb
> +<h2 class="text-page-title">Ruby/Railsテキスト教材</h2>
class に`text-center` を記述すると中央揃えにできるので、そちらを採用してはいかがでしょうか？

2021-07-26 13:00 UTC, great084 approved these changes
LGTMです〜

2021-07-26 13:48 UTC, merged